logging:
  level:
    # логирование выполнения sql скриптов
    org.springframework.jdbc.datasource.init: DEBUG
    # логирование http запросов
    org.zalando.logbook: TRACE

spring:
  sql.init.mode: always # выполнение SQL скриптов для инициализации БД при каждом запуске приложения
  # src/main/resources/schema.sql - создание схемы БД
  # src/main/resources/data.sql - заполнение данными
  datasource:
    # отключение автоматического перевода имен полей и таблиц в верхний регистр
    #url: jdbc:h2:file:./db/filmorate; #DATABASE_TO_UPPER=false;  # сохранение данных в файл
    url: jdbc:h2:mem:./db/filmorate; #DATABASE_TO_UPPER=false;  # сохранение данных в память
    driverClassName: org.h2.Driver
    username: sa
    password: password

  # цветной вывод в консоль
  output.ansi.enabled: ALWAYS